version: '3.1'
services:

    webserver:
      image: 'nginx:alpine'
      working_dir: /application
      container_name: webserver_crawlitchallenge
      volumes:
          - '.:/application'
          - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
          - '3000:80'
      networks:
        - crawlitchallenge

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php_crawlitchallenge
      working_dir: /application
      volumes:
          - '.:/application'
          - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
      networks:
        - crawlitchallenge

networks:
  crawlitchallenge:
    driver: bridge
